[workspace]
authors = ["Pablo Winant <pablo.winant@gmail.com>"]
channels = ["conda-forge"]
name = "t"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.10.8,<4"
pandas = ">=2.3.3,<3"
scipy = ">=1.16.3,<2"
numpy = ">=2.3.5,<3"
requests = ">=2.32.5,<3"
ipykernel = ">=7.1.0,<8"
python = ">=3.14.2,<3.15"
